testScripts/SetupLive.js
Script current creates a live stream on https://core.test.contentfabric.io/#/apps/fabric-browser/content/ilibX37dYK6dj5F5ZQQC4eDLMNe1kZD
You just need to have an account for the private key
```
$ export PRIVATE_KEY=deadbeefbadf00dbadf00dbadf00dbadf00dbadf00dbadf00dbadf00dbadf00d
$ node SetupLive.js 
Fabric URI: https://host-35-246-28-142.test.contentfabric.io
Ethereum URI: https://host-35-246-28-142.test.contentfabric.io/eth/
WARNING: Multiple definitions for canPublish
WARNING: Multiple definitions for canPublish
Object ID: iq__41wzNorYAwEWQKrvjYX4cBPPs5cQ
Edge token: tqw_DzZkjGGH6BXQbUPuSCZboX6MLxFPsvdG8
Object hash: hq__8eeWx4gymovm7ozro8ieULzYJyUQj7EHq6Sq6DbFKDAE6dp8XCDkeY1J8MUymXkird4nWmnBsa
Set Authorization header:
export AUTH_HEADER="Authorization: Bearer …
```
=> Script to create live object

docs/abr/index.md, testScripts/OfferingAddSampleAes.js, testScripts/OfferingAddVideoRung.js, testScripts/OfferingListRungs.js, testScripts/OfferingRemoveVideoRung.js, testScripts/parentClasses/ScriptBase.js, testScripts/parentClasses/ScriptOffering.js
Add new scripts OfferingAddVideoRung.js,, OfferingListRungs.js, OfferingRemoveVideoRung.js
Update ABR documentation to include the new scripts.
Add validation helpers to ScriptBase.js
Add error message helper to ScriptBase.js to make error messages easier to read
=> Add new scripts OfferingAddVideoRung.js,, OfferingListRungs.js, OfferingRemoveVideoRung.js

docs/abr/index.css, docs/abr/index.html, docs/abr/index.md
* Add "Basic Concepts" section
* Minor revisions to other sections
* Add bullets to unordered lists
* Escape text containing underscores
=> Changes to  ABR doc

src/client/ABRPublishing.js, testScripts/CreateABRMezzanine.js, testScripts/OfferingAddTextWatermark.js, testScripts/OfferingEditStreamAttrs.js, testScripts/abr_profile_both.json, testScripts/abr_profile_clear.json, testScripts/abr_profile_drm.json, testScripts/parentClasses/ScriptBase.js
Add new aspect ratio to abr_profile_*.json
Plumb through encryption in ABRPublishing.js#CreateProductionMaster() for S3 copies
Make --wait option visible in listed options for CreateABRMezzanine.js
Fix message in OfferingAddTextWatermark.js when an image watermark already exists
New script OfferingEditStreamAttrs.js
Change sample network fabric configuration url printed by ScriptBase.js help text to demo network
Fix ESLint complaints in OfferingAddTextWatermark.js
=> Fix --encrypt --s3-copy combo when creating production masters, + other misc. ABR script changes

docs/ElvClient.html, docs/ElvClient.js.html, docs/UserProfileClient.html, docs/UserProfileClient.js.html, src/AuthorizationClient.js, src/ElvClient.js, src/EthClient.js, src/HttpClient.js, src/LogMessage.js, src/UserProfileClient.js
Extract common code used in Log() methods to /src/LogMessage.js
Update docs for ToggleLogging()
=> Add support for custom debug log handlers

testScripts/SetupLive.js
- Modifications needed to work with qfab develop branch.
=> Modifications for rtmp live streaming

testScripts/InitializeTenant.js
Helps get new customers up to speed more quickly
=> Add fabric config url to InitializeTenant output, add standard DRM cert to metadata of Title Mezzanines library

src/client/AccessGroups.js, testScripts/InitializeTenant.js
Also minor output consistency fix for InitializeTenant.js
=> SetGroupPermission - improve err msg on bad group address

docs/ElvClient.js.html, src/ElvClient.js, utilities/ChannelStartVaLOffering.js, utilities/OfferingUpdateCrfBitrate.js
src/, docs/
* fix double-escape of newline/tab in 'Debug Logging Enabled' message
utilities/
* Rename ChannelStartLiveOffering.js to ChannelStartVaLOffering.js, update playout type to "ch_val"
* New script OfferingUpdateCrfBitrate.js to fix x265 mezzanine offerings generated using CRF
=> Misc changes - ChannelStartLiveOffering,  OfferingUpdateCrfBitrate, 'Debug Logging Enabled' message

docs/abr/index.html, docs/abr/index.md, package.json, src/client/Files.js, testScripts/OfferingAddCaptionStream.js, testScripts/abr_profile_both.json, testScripts/abr_profile_clear.json, testScripts/abr_profile_drm.json, utilities/ChannelCreate.js
Update jsonpath-plus pkg version to pull in security fixes
src/
* Fix documentation for 'encryption' parameter options (change `'none (default)'` to `'none' (default)`) in Files.js
docs/abr
* update markdown and html files with info on adding captions
testScripts/
* Add entries for square video to non-4K ABR profile JSON files
* Add `--encrypt` parameter to OfferingAddCaptionStream.js
utilities/
* Fix /public/ offerings link in ChannelCreate.js
=> Add caption/subtitle info to ABR docs, + misc minor fixes and enhancements

src/client/ContentManagement.js
Update CopyContentObject to account for cap keys.
General flows for copying a content object:
1. If no cap keys present, create and finalize object using 'copy_from' param.
2. If user cap present, replace object id in encryption and replace in metadata before finalizing object.
3. If kms cap present, set permission to 'owner' upon creation and then set permission to create a new kms cap.
4. If kms cap and user cap present, 2 and 3 apply.
Relates to https://github.com/eluv-io/elv-fabric-browser/issues/8
=> Finalize CopyContentObject method

src/walletClient/Configuration.js, src/walletClient/index.js
https://github.com/qluvio/elv-apps-projects/issues/14
=> Wallet Preview 

src/FrameClient.js
Fix for large file uploads in FrameClient
=> Fix for FilesUpload with large files

src/FrameClient.js
Forgot to add this.Crypto to FrameClient
=> Add Crypto to FrameClient so UploadFiles can do encrypted

testScripts/DraftFinalize.js, testScripts/OfferingEnsureStrongDrm.js, testScripts/abr_profile_4k_both.json, testScripts/abr_profile_4k_clear.json, testScripts/abr_profile_4k_drm.json, testScripts/abr_profile_both.json, testScripts/abr_profile_clear.json, testScripts/abr_profile_drm.json, utilities/WriteTokenDecode.js, utilities/example_files/abr_profile_4k_both.json, utilities/example_files/abr_profile_4k_clear.json, utilities/example_files/abr_profile_4k_drm.json, utilities/example_files/abr_profile_both.json, utilities/example_files/abr_profile_clear.json, utilities/example_files/abr_profile_clear_hls_only.json, utilities/example_files/abr_profile_drm.json, utilities/example_files/abr_profile_drm_hls_only.json, utilities/lib/concerns/Draft.js
* Add new scripts 
* testScripts/DraftFinalize.js (finalize draft for a given write token)
* utilities/WriteTokenDecode.js (decode a write token and output info)
* testScripts/OfferingEnsureStrongDrm.js (remove playout formats other than widevine/fairplay)
* Change sample ABR profile JSON files
* Set stereo (2-channel) audio bitrate to 192kbps
* Add surround (6-channel) audio entry with bitrate 384kbps
* Remove 4-channel audio entries
=> Add several new scripts, edit audio entries in ABR Profile JSON files

testScripts/InitializeTenant.js
Do not set a display app in InitializeTenant script.
Relates to #155
=> Remove display app from title master type

src/ElvClient.js, src/FrameClient.js
Include search URIs within Nodes() return data.
Add RecordWriteToken to FrameClient methods.
=> Nodes() search uris and write token

src/client/ContentManagement.js
Reverts eluv-io/elv-client-js#209
=> Revert "Return nodeUrl when calling CreateContentObject, improve protection against concurrency issues"

src/client/Files.js
Files.js#UploadFiles() - Catch and re-raise exception if PrepareJobs() encounters error (fixes stuck condition if file becomes unavailable during upload)
=> Files.js#UploadFiles() - Catch and re-raise exception if PrepareJobs() fails

src/client/ContentManagement.js
`accountAddr` wasn't properly intialized in CreateContentType in [pull request 233](https://github.com/eluv-io/elv-client-js/pull/233)
=> CreateContentType bug fix

src/FrameClient.js, src/client/ContentAccess.js
Add `EmbedUrl` for creating an embeddable url. Will be used in Stream Sample, Media Ingest, and Video Editor.
=> Add EmbedUrl to return an embeddable url

src/client/ContentAccess.js
Fix the `controls` value passed to set the url param.
=> Fix EmbedUrl controls value

src/client/LiveConf.js
Replace LiveConf LadderTemplate 360 rung with 540 low per elv-live-js change: https://github.com/eluv-io/elv-live-js/pull/151
=> Update LiveConf ladder

src/FrameClient.js, src/walletClient/ClientMethods.js, src/walletClient/index.js
Allows clients to get all owned nfts and their full info/metadata
=> Add UserNFTs method (/as/apigw/nfts)

src/walletClient/Utils.js, src/walletClient/index.js
Also include nft_template in the result, if it's present
=> Pass "owned-full-meta" requests thru FormatNFT.

src/client/ContentAccess.js
Added support for ticket codes auth.
=> Extend EmbedUrl to support ticket codes

src/FrameClient.js, src/client/LiveConf.js, src/client/LiveStream.js
Changes:
- Add srt support to Live Stream `StreamConfig` api.
- Move /probe to /live_recording/probe_info
Relates to https://github.com/qluvio/elv-apps-projects/issues/235
=> Add srt support for live stream

src/ElvClient.js, testScripts/CreateAndDecodeSignedMessage.js, utilities/GenerateFabricToken.js
matching authd PR is https://github.com/qluvio/elv-master/pull/1128
=> initial implementation of signed message create and decode functions

src/client/ContentManagement.js
A 404 error here is expected - printing it to the console when using CLI commands is too confusing.
=> Remove PublishContentVersion console.error

src/client/LiveConf.js, src/client/LiveStream.js
Set live stream reconnect timeout to 10 minutes
=> Set live stream reconnect timeout default ; Remove config timeout

src/abr_profiles/abr_profile_live_drm.js, src/client/LiveStream.js
Add DASH format to live stream configuration.
=> DASH support for live streams

src/client/LiveStream.js
Return inactive state when the edge write token metadata read fails. This may need additional logic to match the appropriate error code(s).
=> Return inactive state when edge write token meta read fails

src/client/LiveConf.js, src/client/LiveStream.js
- Support forensic watermark
- Change watermark path to live_recording/playout_config
=> Live stream watermark changes

src/AuthorizationClient.js, test/ElvClient.test.js, test/utils/Utils.js
* **Before:**
```
elv-utils-js/utilities [main]  % node MetaSet.js --path /test --metadata '{"x":"y"}' --objectId iq__2Cr4ULufAWhX8fdU49Kh1Zqc5tL
Set metadata at /test for object iq__2Cr4ULufAWhX8fdU49Kh1Zqc5tL
Initializing elv-client-js... (config URL: https://main.net955305.contentfabric.io/config)
Looking up library ID for object iq__2Cr4ULufAWhX8fdU49Kh1Zqc5tL...
Found library ID: ilib2P8qTRhtcgrY4wafJNFi4cj1jDR8
Retrieving existing metadata from object...
Retrieving metadata from object iq__2Cr4ULufAWhX8fdU49Kh1Zqc5tL...
Getting write token...
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"execution reverted","code":"UNPREDICTABLE_GAS_LIMIT","method":"estimateGas","t …
```
=> Replace 'UNPREDICTABLE_GAS_LIMIT' with a permission denied message.

src/client/ContentManagement.js
Change is to help prevent errors in customer objects where creator does not initially create encryption conk, then some other user does something that causes encryption conk to get added to object.
**Main changes - ContentManagement.js**
- Create encryption conk by default when creating a new object
- Add option `noEncryptionConk` to `CreateContentObject()` to force old behavior
- Add option `createKMSConk` to `CreateContentObject()`
**Unrelated JSDoc fix in same source file**
- `CreateContentLibrary()` (tenantId vs. tenantContractId, imageName not showing up in final html)
**Minor changes to resolve warnings from IDE for same source file**
- Accept IDE suggestion to use brackets rather than single-characters + 'or' in regex (change `\/|\.` to `[/.]`)
- Edit `DeleteContentLibrary()` to …
=> Create encryption conk by default when creating object
