testScripts/SetupLive.js

Add script for creating live HLS and UDP TS stream objects
Note: This is the same script as the one in the test-tool branch, which probably can be deleted/archived now.

testScripts - script to create live streams

---

src/AuthorizationClient.js

Initial implementation of auth'd key API request.
Corresponds to new API's in `elv-master` - previous API's are still supported for backward compatibility.

Prelim impl of support for auth'd key API.

---

testScripts/AddGroupPermissions.js
testScripts/CreateABRMezzanine.js
testScripts/CreateProductionMaster.js
testScripts/EditContent.js
testScripts/ProductionMasterInit.js

modify ProductionMasterInit.js to use yargs and use named options rather than positional arguments
add support for --config-url: EditContent.js, ProductionMasterInit.js
add support for --elv-geo: ProductionMasterInit.js
add --config-url to 'Usage' string: CreateABRMezzanine.js, CreateProductionMaster.js, EditContent.js, ProductionMasterInit.js
add --elv-geo to 'Usage' string: CreateProductionMaster.js, ProductionMasterInit.js

add testScripts/AddGroupPermissions.js

---

testScripts/MezzanineStatus.js
testScripts/OfferingAddClear.js
testScripts/OfferingAddSampleAes.js
testScripts/OfferingCopy.js
testScripts/OfferingRemoveClear.js
testScripts/parentClasses/MetadataMixin.js
testScripts/parentClasses/ScriptBase.js
testScripts/parentClasses/ScriptOffering.js

Fix usage and error messages in MezzanineStatus.js
Add new commands to testScripts/
* OfferingAddClear.js - adds DRM-free playout formats to an offering
* OfferingAddSampleAes.js - copies adds HLS SampleAes DRM playout format to an offering (must already have an HLS AES-128 playout format)
* OfferingCopy.js - copies an existing offering to another offering key (overwrites any existing offering under the target key)
* OfferingRemoveClear.js - removes playout formats that do not have DRM from an offering
Add parent and mixin classes to refactor common code for command line arguments and other frequently used operations, with an eye towards eventually refactoring the rest of the items under testScripts/

Add new commands for manipulating ABR mezzanine offerings

---

src/client/ABRPublishing.js
src/client/Files.js
testScripts/CreateABRMezzanine.js
testScripts/CreateProductionMaster.js
testScripts/EditContent.js
testScripts/ProductionMasterInit.js

Additions to support creation of Production Masters containing files from multiple S3 buckets (and creation of ABR Mezzanines from those masters):
* Allow use of full s3://BUCKET_NAME/rest/of/path strings to refer to items in S3 (affects CreateProductionMaster(),  UploadFilesFromS3(), CreateProductionMaster.js, EditContent.js). Existing convention of omitting 's3://BUCKET_NAME/' from start of path still works.
* Allow loading S3 credential sets from a JSON file with --credentials (affects CreateProductionMaster(), StartABRMezzanineJobs(), CreateProductionMaster.js, CreateABRMezzanine.js, ProductionMasterInit.js) - if not supplied, fall back to using environment variables as a 1-element credential set.
Fix problem with EditContent.js when uploading S3 files.
Ensure correct prod_master_hash …

Support production masters containing files from multiple S3 buckets, + minor fixes

---

package.json
testScripts/OfferingAddCaptionStream.js

Note that new package Slugify added as dev dependency is not actually used to generate a slug in the conventional sense, it is just a convenient way to create a JSON key that does not conflict with existing keys (for the new caption stream)

Add new ABR script OfferingAddCaptionStream.js

---

testScripts/MezzanineMigrateDrmKeys.js

Adds /testScripts/MezzanineMigrateDrmKeys.js, which edits object and calls Gilles' API method that regenerates DRM keys (preserving existing key IDs) and stores under new /elv/crypt/drm/kids metadata key (removes from old location /playout_drm_keys)

Add script to migrate mezzanine DRM keys

---

testScripts/CreateABRMezzanine.js
testScripts/CreateProductionMaster.js
testScripts/MezzanineStatus.js
testScripts/ObjectDelete.js
testScripts/ObjectSetImage.js
testScripts/OfferingAddCaptionStream.js
testScripts/OfferingRemoveHls.js
testScripts/VariantAddStream.js
testScripts/VariantChangeStreamSource.js
testScripts/abr_profile_4k_both.json
testScripts/abr_profile_4k_clear.json
testScripts/abr_profile_4k_drm.json
testScripts/abr_profile_both.json
testScripts/abr_profile_clear.json
testScripts/abr_profile_drm.json
testScripts/parentClasses/ScriptBase.js
testScripts/parentClasses/ScriptVariant.js

* Add new entries to ABR profiles (new aspect ratios encountered in customer files, entry for mono audio)
* Ensure that ip-title-id is JSON encoded as a string even when it looks like a number to javascript
* Add --force option to MezzanineStatus.js to allow finalizing even if LRO info looks incorrect (i.e. status stopped updating, or progress percentage not = 100%)
* Add --isDefault arg to OfferingAddCaptionStream.js
* Fix handling of VTT caption file timestamps that don't contain digits for hour
* Add new utilities in /testScripts for workflow automation
* ObjectDelete.js
* ObjectSetImage.js (sets thumbnail to existing file in object)
* OfferingRemoveHls.js (removes any HLS playout formats from offering)
* VariantAddStream.js (includes support for mixing 2 mono streams into 1 stereo …

Various script enhancements, primarily for ABR video

---

src/EthClient.js

Automatically retry contract method call when "nonce has already been used" error is returned.
Logger shows method call, followed by a retry and then a successful transaction receipt.
Relates to https://github.com/eluv-io/elv-fabric-browser/issues/17

Auto-retry contract method call on nonce expired error

---

src/client/ABRPublishing.js
utilities/MezzanineCreate.js

Do not concatenate lists when the same key is present in old metadata and new "to-merge" metadata (and both values are lists), instead replace old value with new.
(use Ramda's DeepMergeRight - https://ramdajs.com/docs/#mergeDeepRight )

ABRPublishing.js - Change metadata merge behavior for CreateABRMezzanine

---

src/client/ContentManagement.js

Create clearer error messaging for content creation when the current account has no contribute permission.
Check for permission before attempting to call contract method.
Relates to #130

Better error messaging for content creation with no permission

---

src/AuthorizationClient.js

Fix issue when creating Production Master with --encrypt: ReferenceError: client is not defined @ AuthorizationClient.GenerateAuthorizationToken (elv-client-js/src/AuthorizationClient.js:180:24)

PR fix create master encrypted

---

src/client/ContentManagement.js

Add a string param for the tenant ID to CreateContentLibrary. This will be a required field in the fabric browser.

Add tenantId param to CreateContentLibrary

---

src/UserProfileClient.js
src/Utils.js
src/client/ContentManagement.js

This PR addresses three items:
- Add ValidAddress for verifying that an address is the correct format. This function uses Ethers.utils.getAddress.
- Add ValidHash for verifying that a hash is the correct format.
- Validate tenant hash when creating a library and setting the tenant ID.
Validation errors in the fabric browser

Add ValidAddress, ValidHash methods and validate tenant hash

---

package-lock.json
package.json
src/client/ABRPublishing.js
testScripts/VariantABRProfile.js
utilities/SimpleIngest.js

* Add `hash` to data returned by `ABRPublishing.js#StartABRMezzanineJobs()`
* Add @eluvio/elv-abr-profile as dependency
* New script `testScripts/VariantABRProfile.js`: outputs ABR Profile for a given production master object's default variant, generated from default Eluvio parametric bitrate ladder and tailored for the variant's video stream characteristics
* New script `utilities/SimpleIngest.js`: one-step ingest creating a single object that is both master and mezzanine, using a parametric bitrate ladder retrieved from the target library's metadata

Add scripts using new ABR profile generation package '@eluvio/elv-abr-profile'

---

README.md

Add extra steps for the case of an `unsupported architecture` error on Mac OS X.

Add readme steps if unsupported arch error

---

src/client/ContentAccess.js

Add a `clearCache` option to `Permission()` and `Visibility()` that deletes the visibility info cached for a given address so that the call is made and result updated.
Relates to https://github.com/eluv-io/elv-fabric-browser/issues/41

Add option to clear visibility cached by address

---

src/client/ContentManagement.js

Decrypt, update object id, and re-encrypt user cap when copying a content object. Currently, this was only happening for owner caps.

Decrypt and encrypt conk for all caps during copy

---

src/client/ContentManagement.js

Use existing link metadata if it exists so other data doesn't get removed.

Use existing link when creating auth token

---

src/ElvClient.js
src/FrameClient.js
src/HttpClient.js
src/client/ContentManagement.js

Add `clientMode` to the ElvClient constructor, which is set to "default" if no value is provided. When clientMode === "search", the HttpClient uris are set to use the searchUris. Otherwise, the fabricUris are used.
This allows calling CallFromFrameMessage from the appropriate client in elv-core-js.
Additionally, remove `RecordWriteToken` from allowed FrameClient methods.

Add service param to ElvClient

---

src/client/ContentManagement.js

* Add nodeUrl to object returned by CreateContentObject()
* streamline code in EditContentObject for obtaining node URL from http response
* Improve protection against concurrency issues if failover occurs (use node URL obtained from http response when calling RecordWriteToken())

Return nodeUrl when calling CreateContentObject, improve protection against concurrency issues

---

src/client/ContentManagement.js

* Add nodeUrl to object returned by CreateContentObject()
* streamline code in EditContentObject for obtaining node URL from http response
* Improve protection against concurrency issues if failover occurs (use node URL obtained from http response when calling RecordWriteToken())

Add nodeUrl to return value of CreateContentObject(), improve safety against concurrency issues (RecordWriteToken) (#211)

---

src/client/ContentManagement.js

When `duration` is not provided to GenerateSignedLinksToken(), set `exp` as undefined instead of an empty string. Relates to https://github.com/eluv-io/elv-fabric-browser/issues/33#issuecomment-1485965313

Pass undefined exp to GenerateSignedLinkToken when not provided

---

src/client/ContentAccess.js

Add try/catch to contract method call for "countVersionHashes" to show proper error for a deleted object.
Relates to https://github.com/eluv-io/elv-fabric-browser/issues/79

Catch error for countVersionHashes to throw proper error message

---

src/client/ContentAccess.js

When an item has been deleted, countVersionHashes returns `undefined`, which causes `versionCount.toNumber()` to throw a type error. Handle this case so that the correct error message is displayed to the user.

Handle latest version hash error when versionCount is undefined

---

typeSpecs/Default.js
typeSpecs/MainSite.js

This will be used in Asset Manager when initializing searchable link values and in the event of loading a Default profile.

Add searchable_links to defaultSpec

---

src/ElvClient.js
src/UserProfileClient.js
src/Validation.js
src/client/AccessGroups.js
src/client/ContentAccess.js
src/client/ContentManagement.js
test/ElvClient.test.js
testScripts/InitializeTenant.js

[ISSUES #398](https://github.com/qluvio/info/issues/398)
- Change `tenant` to `tenant admins` or `tenant` to `tenant contract` in comments/code for clarity.
- Add functions `tenantContractId` and `setTenantContractId` to retrieve/set `_ELV_TENANT_ID `from user's metadata.
- In CreateContentLibrary, first check if the user is associated with a tenant, then check if they are in either the tenant's content admins group or tenant admins group. Throw an error if any of the conditions are not met.
- Add _ELV_TENANT_ID to library's metadata when created.
- Created helper functions to aid the procedures above (IsTenantAdmin, IsContentAdmin).
- Add _ELV_TENANT_ID to contentType's metadata when created.
- Add libraryVerification to functions.

Issue #398 - Library Contract with _ELV_TENANT_ID

---

typeSpecs/Default.js

This is used to set default values when the Searchable Links control setting is checked within Content Type configuration.

Change searchable link default value

---

src/Validation.js

Added a few new 'content part' prefixes.
Content Fabric reference:  https://github.com/eluv-io/common-go/blob/ad39b8825f76ca44ca45cd56a6424687e783b34b/format/hash/hash.go#L125C1-L125C1

Add valid part hash prefixes

---

src/client/LiveConf.js
src/client/LiveStream.js

Deep copy LiveconfTemplate to avoid object values (ladder specs in particular) from being cached from multiple times applying configuration to a stream.

Deep copy Live conf template when generating config

---

src/client/LiveConf.js

Set live stream audio seg duration to a fixed value of `29.76*48000` instead of being based on video frame rate.
Relates to https://github.com/eluv-io/elv-live-js/issues/153

Fix live stream audio seg duration

---

src/FrameClient.js
src/client/Contracts.js

This is a proxy method that allows determining whether a contract is v3 (as well as other contract info) in FrameClient.
Relates to https://github.com/eluv-io/elv-fabric-browser/issues/80

Add ContractInfo proxy method to Contracts

---

src/walletClient/ClientMethods.js
src/walletClient/index.js

Currently, RedeemableOfferStatus will return the same response (`{ status: "unknown" }`) for 2 different states:
1) Offer redemption not started
2) Redemption pending but not completed
That's because the `extra` field doesn't exist until redemption completes, so RedeemableOfferStatus can't find the offer in the "pending" state.

Add offerId to MintingStatus result for op=nft-offer-redeem

---

src/client/Contracts.js

When we do `json.stringify()` in `ReplaceMetadata` method, it adds double quotes to string. So, calling the method directly. 
@elv-kevin should we update `ReplaceMetadata` method to handle string data or is this the right way?

fix tenant contract metadata

---

src/client/LiveConf.js
src/client/LiveStream.js

Live streams now support new configuration options to set the video stream timebase and frame duration (in ts units).
Adapt the live stream configurator to use these new settings where necessary.  This makes it so RTMP streams create mez recordings with regular frame durations and support copy-to-vod.
Note RTMP 29.97 and 59.94 fps don't work properly with the video timebase setting and they are left unchanged.

Live stream configuration using video timebase and frame duration

---

src/client/ContentAccess.js
src/client/ContentManagement.js

The qfab APIv2 has an SSE (server-sent event) API for commit events - that is a little harder to implement and also of course is not compatible to the current API.
I propose we add a simple additional check, to wait for the qfab API to confirm the hash, which happens shortly after the blockchain confirmation.
This way there is very little additional waiting time for commits and the client works correctly with both API v1 and v2.
Once APIv2 is deployed fully and support for APIv1 is no longer require, change to use the server-sent event watcher which reduces blockchain calls and is the most immediate.

Support qfab APIv2 commits using a simple additional check

---

src/client/LiveConf.js
src/client/LiveStream.js

To support multiple audio streams, live_recording metadata changed and is not backward compatible.
Add support for a new configuration structure:
```json
{
"audio" {
"1" : {  // This is the stream index
"tags" : "language: english",
"codec" : "aac",
"bitrate": 204000,
"record":  true,
"recording_bitrate" : 192000,
"recording_channels" : 2,
"playout": true,
"playout_label": "English (Stereo)"
},
"3": {
...
}
}
}
```

Add live stream support for multi audio

---

test/utils/Utils.js

required when we update the mining of the blocks to 3s.

add wait for tx receipt in elv-client-js tests

---

test/ElvClient.test.js
test/Utils.test.js
test/utils/Utils.js

In order to test against particular fabric or ethereum url, we can specify it in `TestConfiguration.json` file  as shown below or as environment variables `FABRIC_URL` and `ETH_URL`.
Example TestConfiguration.json file:
```
{
"config-url": "https://demov3.net955210.contentfabric.io/config",
"eth-url": "https://host-76-74-28-234.contentfabric.io/eth/",
"fabric-url": "http://dev-001.dv3.local:8008"
}
```
Initially, it reads all the data from the standard `config-url`. If FABRIC_URL and ETH_URL are set, it updates the node details accordingly. In above example, it reads data from the demov3 network and updates the Fabric and Ethereum nodes to the provided values.

update to TestConfiguration file

---

src/ElvClient.js
src/client/LiveStream.js
test/ElvClient.test.js

Replace SpaceNodes functionality with a call to /nodes for a list of all nodes of the content space and /nodes/:id to retrieve a specific node.
If matchEndpoint is provided, list of nodes will be filtered by that endpoint AND a node id if matchNodeId is also provided.
Otherwise, if matchNodeId is provided, /nodes/:id is called directly and the response is returned as an array.
NOTE: Nothing uses "cbor-web" or "cbor-x" anymore but ContentObjectVerification uses "cbor".

Replace SpaceNodes logic with /nodes and /nodes/:id api's

---

SampleTestConfiguration.json
test/ElvClient.test.js
test/PermissionsClient.test.js
test/utils/Utils.js

https://github.com/eluv-io/elv-client-js/issues/276
* uses `tenant-contract-id` provided as enviroment variable or in config file (added sample config).
```
let tenantContractId = process.env["TENANT_CONTRACT_ID"] || ClientConfiguration["tenant-contract-id"] || "";
```
* checks if the private_key provided is tenant root key.
* checks if the tenant admin group is set for tenant contract id provided.
* reduced the funds to 0.2elv for all tests. 
* Tested in local dev setup.

Update test to use existing tenant contract id

---

src/ElvClient.js
src/Validation.js
src/client/Files.js

* `ListFiles()` changes:
* Add support for getting info from a draft using a `writeToken`
* Add support for requesting a list from a subdirectory using `path` (return value will be recursive list)
* Change URL to Files API version2 
* Protect against tampering of `networks` var by having `Networks()` return a copy of the object rather than original
* Fix  'type coercion' warning  (`==` vs `===`) in `UploadFileData()`

Update ListFiles() to support write token, path, Files API v2. Protect against pollution of Networks()

---

src/client/LiveStream.js

The LRO now includes more specific status information about video and audio recording.

Live stream - report recording status from LRO

---

src/EthClient.js
src/HttpClient.js
src/Utils.js
src/client/ContentAccess.js
src/client/ContentManagement.js
src/client/Files.js

Changes to provide additional info in debug log output:
- HttpClient
- Add logging of fetch parameters by `HttpClient.Request()`
- Allow selected functions to log JSON response body obtained from `HttpClient.Request()` *(requires modification of calling function)*
- Implemented via new function `HttpClient.RequestJsonBody()` that can substitute for `Utils.ResponseToJson(HttpClient.Request(...))` _(couldn't just put the log statement directly inside `HttpClient.Request()` because response body cannot be consumed twice)_
- To have a function support logging response body, modify to use `RequestJsonBody(...)` instead of `ResponseToJson(Request(...))`
- ElvClient
- Modified the following functions to use `HttpClient.RequestJsonBody()` instead of …

Allow debug logging of fetch params and (some) JSON and text response bodies

---

src/client/LiveStream.js

Use URL constructor to parse live stream URL hostname in order to match the node returned by SpaceNodes.
Cases tested:
- "rtmp://host-76-74-28-234.contentfabric.io/rtmp/6Sada7R4"
- "rtmp://host-76-74-28-234.contentfabric.io:1935/rtmp/6Sada7R4"
- "srt://host-76-74-28-235.contentfabric.io:11001?mode=listener"
- "srt://host-76-74-28-235.contentfabric.io?mode=listener"
- "udp://host-76-74-28-234.contentfabric.io:11041"
- "udp://host-76-74-28-234.contentfabric.io"

Parse hostname from live stream url to match node

---

src/client/ContentManagement.js
testScripts/BasicObjectOperations.js

1. **testScripts/BasicObjectOperations.js**: To track the time taken by create, finalize and edit content methods in tv4 or dv3.
2. **Update `PublishContentVersion` to:**
* manage block re-org by filtering `VersionConfirm` events and the `object hash` starting from last 10 blocks.
* introduced a 2-minute timeout for the loop to prevent continuous retries in case events are not found.

Add objects basic operations script and update publishContentVersion method

---

testScripts/BasicObjectOperations.js
testScripts/ObjectDownloadMedia.js
testScripts/OfferingDownloadMedia.js

The script `OfferingDownloadMedia` performs the following:
* Retrieves streams metadata from either `transcodes` or `offerings` for each provided streamKey.
* Then downloads the parts, concatenates them, and trims the media file for each streamKey.
* export PRIVATE_KEY="xxx"
* set demov3 network in TestConfiguration.json or using --config-url
* Run the command:
```
node ./testScripts/OfferingDownloadMedia.js 
--startTime 10 
--endTime 50 
--objectId=iq__bSS84FakdSgxHSiW3kJcA1obH6P 
--out ./out_dir 
--config-url "https://demov3.net955210.contentfabric.io/config"
--streamKey "video,polish_5_1,english_stereo"
```
* For each content with a startTime and endTime, a new folder will be created under the output directory, as shown below:
```
./out_dir
└── …
```

Download media object

---

src/client/LiveConf.js

Allow connection_timeout setting during StreamConfig to avoid overriding with the LiveConf default.

Allow StreamConfig connection_timeout setting

---

utilities/GenerateEditorSignedAccessToken.js

This utility creates a simple ESAT (editor-signed access token) that doesn't require a policy - simply gives access to one object.
When using an access policy, the editor-signed access token may contain more specific access information such as a list of content objects, specific metadata paths, specific offerings, etc.  This feature will be added in a future PR for this file.

Add simple utility GenerateEditorSignedAccessToken.js

---

src/client/ContentAccess.js

I previously used wrong path syntax in the call to objectPath.get(), failing to detect when cause of error was 'write token not found' (as opposed to the requested path not existing in the metadata). 
This resulted in `{}` getting returned instead of throwing an error.
Intended behavior was to throw an error if the node could not find the write token.

Fix check for 'write token not found' in ContentAccessMetadata()

---

utilities/GenerateFabricToken.js

I use this when swapping between private keys to put a token in my env for curl dev use; need the ENV part.  and for convenience use the ctx part so it's easy to set some info for elv tools decode.

add optional args to GenerateFabricToken

---

src/client/ContentManagement.js

When `options.createKMSConk===undefined`  this value was getting overridden by default `true` in cases where `CreateContentObject()` calls `CreateEncryptionConk()`

Fix handling of undefined `options.createKMSConk` in `CreateContentObject()`

---

src/client/Contracts.js
test/ElvClient.test.js

To address: https://github.com/qluvio/content-fabric/issues/3317
The `ObjectCleanup` method addresses an issue where the deleted objects continued to appear in the user listings due to references in the `access_indexor` contract. It removes entries for deleted objects so that they no longer appear in Frowser post-cleanup.
* It accepts:
* Object ID, version hash, or contract address (can be user address or contract)
* Object type: "library", "content_object", "group", "content_type", or "all"
* When a **user address** is provided, it performs cleanup for the user and all associated groups concurrently.
* Example output:
```json
{
"0xC9f6BF00aBb5CCD35116760D2A0a5E64b617B84c": {
"beforeCleanup": {
"contentObjectsLength": 324
},
"afterCleanup": {
"contentObjectsLength": 323
}
},
"groups": { …
```

Object cleanup and Test fixes
